In [83]:
import numpy as np
import pandas as pd

In [27]:
df= pd.read_csv(r'C:\Users\chat2\OneDrive\Documents\udemy_dataset\Data_Preprocessing\Data.csv')
df

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [121]:
df2=df.copy()
df3=df.copy()

In [13]:
df2['Salary'].isnull()

df2['Salary'].fillna(df2['Salary'].median(),inplace=True)

In [14]:
df2['Salary'].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
Name: Salary, dtype: bool

In [45]:
from sklearn.impute import SimpleImputer
x=df2.iloc[:,1:2].values
x


array([[44.],
       [27.],
       [30.],
       [38.],
       [40.],
       [35.],
       [nan],
       [48.],
       [50.],
       [37.]])

In [46]:
imputer= SimpleImputer(missing_values='NaN',strategy='mean')
imputer= imputer.fit(x)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [70]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
lbl_encoder=LabelEncoder()
X=df2.iloc[:,0].values
df2.iloc[:,0]=lbl_encoder.fit_transform(X)
X_array=df2['Country'].values
X_array

array([0, 2, 1, 2, 1, 0, 2, 0, 1, 0], dtype=int64)

In [139]:
one_encoder=OneHotEncoder(sparse=False)
X_array_encoded=X_array.reshape(len(X_array),1)
df2=one_encoder.fit_transform(X_array_encoded)
dp=pd.DataFrame(df2)
result=pd.concat([dp,df3.iloc[:,1:3]],axis=1)
result

C:\Users\chat2\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


0    1    2   Age   Salary
0  1.0  0.0  0.0  44.0  72000.0
1  0.0  0.0  1.0  27.0  48000.0
2  0.0  1.0  0.0  30.0  54000.0
3  0.0  0.0  1.0  38.0  61000.0
4  0.0  1.0  0.0  40.0      NaN
5  1.0  0.0  0.0  35.0  58000.0
6  0.0  0.0  1.0   NaN  52000.0
7  1.0  0.0  0.0  48.0  79000.0
8  0.0  1.0  0.0  50.0  83000.0
9  1.0  0.0  0.0  37.0  67000.0

In [142]:
X=result.iloc[:,:-1]
Y=result.iloc[:,-1]
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,Y,test_size=0.2)
x_train

0    1    2   Age
2  0.0  1.0  0.0  30.0
0  1.0  0.0  0.0  44.0
3  0.0  0.0  1.0  38.0
1  0.0  0.0  1.0  27.0
8  0.0  1.0  0.0  50.0
9  1.0  0.0  0.0  37.0
6  0.0  0.0  1.0   NaN
5  1.0  0.0  0.0  35.0

In [144]:
from sklearn.preprocessing import StandardScaler
sc_x= StandardScaler()
X_train=sc_x.fit_transform(x_train)
X_test=sc_x.transform(x_test)
X_train

array([[-0.77459667,  1.73205081, -0.77459667, -1.00019229],
       [ 1.29099445, -0.57735027, -0.77459667,  0.92174584],
       [-0.77459667, -0.57735027,  1.29099445,  0.09805807],
       [-0.77459667, -0.57735027,  1.29099445, -1.41203617],
       [-0.77459667,  1.73205081, -0.77459667,  1.7454336 ],
       [ 1.29099445, -0.57735027, -0.77459667, -0.03922323],
       [-0.77459667, -0.57735027,  1.29099445,         nan],
       [ 1.29099445, -0.57735027, -0.77459667, -0.31378582]])